apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: ucp-token-generator
      auth:
        serviceAccount:
          name: "token-generator"
          namespace: ucp-token-generator
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: ucp-token-generator