apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  team-a-kubeconfig
  namespace: ucp-token-generator
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: team-a-project-kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              server: https://platform.tpsm.pvetnz.com/org/59dc0432-1993-43be-a855-b6c4e218b5fa/project/bf3d112c-4438-4d3b-9bdf-810e51e5245a
            name: tanzu-cli-tpsm-80f5cac9:team-a
          contexts:
          - context:
              cluster: tanzu-cli-tpsm-80f5cac9:team-a
              user: tanzu-cli-tpsm-80f5cac9-user
            name: tanzu-cli-tpsm-80f5cac9:team-a
          current-context: tanzu-cli-tpsm-80f5cac9:team-a
          kind: Config
          preferences: {}
          users:
          - name: tanzu-cli-tpsm-80f5cac9-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token

